"""Type stubs for clipper2.z (the USINGZ build: points are (x, y, z), paths are N*3).

Same surface as `clipper2`, with three differences: a point is a 3-tuple on the way out
(upstream's z is int64 in both families, so a D point is `(float, float, int)`), an N*2
input is still accepted and gets z = 0, and `Clipper64` / `ClipperD` / `ClipperOffset` also
carry the z callback.

The enums, `Rect64`, `RectD` and `Clipper2Error` are the very objects `clipper2` exports:
they are registered once, in the non-USINGZ extension. That is why `Rect64.mid_point()`
and `Rect64.as_path()` stay two-dimensional here, and `Rect64.contains()` wants a plain
(x, y). Everything else in this module is a distinct, module-local class: a
`clipper2.PolyPath64` is not a `clipper2.z.PolyPath64`.

Running mypy over these stubs themselves reports `overload-overlap`: an integer input
matches the D overload too (`Sequence[int]` is a `Sequence[float]`, and an integer
array is accepted wherever D is forced), and the 64 form wins by being first --
which is exactly how the binding dispatches. Consumers never see it; only checking
the .pyi files directly does.
"""

from collections.abc import Callable, Iterator, Sequence
from typing import Any, TypeAlias, overload

import numpy as np
from numpy.typing import NDArray

from clipper2 import ClipType as ClipType
from clipper2 import Clipper2Error as Clipper2Error
from clipper2 import EndType as EndType
from clipper2 import FillRule as FillRule
from clipper2 import JoinType as JoinType
from clipper2 import PathType as PathType
from clipper2 import PointInPolygonResult as PointInPolygonResult
from clipper2 import Rect64 as Rect64
from clipper2 import RectD as RectD
from clipper2 import TriangulateResult as TriangulateResult

# --- input aliases: a point may be (x, y) or (x, y, z), a path N*2 or N*3 ---------------

_Point64Like: TypeAlias = Sequence[int] | NDArray[np.integer[Any]]
_PointDLike: TypeAlias = Sequence[float] | NDArray[np.floating[Any]] | NDArray[np.integer[Any]]
_Path64Like: TypeAlias = Sequence[_Point64Like] | NDArray[np.integer[Any]]
_PathDLike: TypeAlias = Sequence[_PointDLike] | NDArray[np.floating[Any]] | NDArray[np.integer[Any]]
_Paths64Like: TypeAlias = Sequence[_Path64Like] | NDArray[np.integer[Any]]
_PathsDLike: TypeAlias = Sequence[_PathDLike] | NDArray[np.floating[Any]] | NDArray[np.integer[Any]]
_GeometryLike: TypeAlias = _PathDLike | _PathsDLike

# --- output aliases ---------------------------------------------------------------------

_Point64: TypeAlias = tuple[int, int, int]
_PointD: TypeAlias = tuple[float, float, int]
_Path64: TypeAlias = NDArray[np.int64]
_PathD: TypeAlias = NDArray[np.float64]
_Paths64: TypeAlias = list[NDArray[np.int64]]
_PathsD: TypeAlias = list[NDArray[np.float64]]

_DeltaCallback: TypeAlias = Callable[[_Path64, _PathD, int, int], float]
# Upstream's callback writes pt.z by reference; here it returns the z of pt.
_ZCallback64: TypeAlias = Callable[[_Point64, _Point64, _Point64, _Point64, _Point64], int]
_ZCallbackD: TypeAlias = Callable[[_PointD, _PointD, _PointD, _PointD, _PointD], int]

CLIPPER2_VERSION: str
CLIPPER2_MAX_DEC_PRECISION: int
MAX_COORD: int
MIN_COORD: int
precision_error_i: int
scale_error_i: int
non_pair_error_i: int
undefined_error_i: int
range_error_i: int

# --- the read-only polygon tree ------------------------------------------------------------

class PolyPath64:
    @property
    def polygon(self) -> _Path64: ...
    @property
    def is_hole(self) -> bool: ...
    @property
    def level(self) -> int: ...
    @property
    def parent(self) -> PolyPath64 | None: ...
    def area(self) -> float: ...
    def child(self, index: int) -> PolyPath64: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PolyPath64: ...
    # Upstream defines only the sequence protocol; `for child in tree` uses it.
    def __iter__(self) -> Iterator[PolyPath64]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class PolyPathD:
    @property
    def polygon(self) -> _PathD: ...
    @property
    def is_hole(self) -> bool: ...
    @property
    def level(self) -> int: ...
    @property
    def parent(self) -> PolyPathD | None: ...
    @property
    def scale(self) -> float: ...
    def area(self) -> float: ...
    def child(self, index: int) -> PolyPathD: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PolyPathD: ...
    # Upstream defines only the sequence protocol; `for child in tree` uses it.
    def __iter__(self) -> Iterator[PolyPathD]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

PolyTree64 = PolyPath64
PolyTreeD = PolyPathD

# --- the engine ------------------------------------------------------------------------------

class ReuseableDataContainer64:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def add_paths(self, paths: _Paths64Like, polytype: PathType, is_open: bool) -> None: ...

class Clipper64:
    preserve_collinear: bool
    reverse_solution: bool
    default_z: int
    def __init__(self) -> None: ...
    @property
    def error_code(self) -> int: ...
    def clear(self) -> None: ...
    def add_reuseable_data(self, reuseable_data: ReuseableDataContainer64) -> None: ...
    def add_subject(self, subjects: _Paths64Like) -> None: ...
    def add_open_subject(self, open_subjects: _Paths64Like) -> None: ...
    def add_clip(self, clips: _Paths64Like) -> None: ...
    def set_z_callback(self, callback: _ZCallback64 | None) -> None: ...
    def execute(self, clip_type: ClipType, fill_rule: FillRule) -> tuple[_Paths64, _Paths64]: ...
    def execute_tree(
        self, clip_type: ClipType, fill_rule: FillRule
    ) -> tuple[PolyPath64, _Paths64]: ...

class ClipperD:
    preserve_collinear: bool
    reverse_solution: bool
    default_z: int
    def __init__(self, precision: int = 2) -> None: ...
    @property
    def error_code(self) -> int: ...
    def clear(self) -> None: ...
    def add_reuseable_data(self, reuseable_data: ReuseableDataContainer64) -> None: ...
    def add_subject(self, subjects: _PathsDLike) -> None: ...
    def add_open_subject(self, open_subjects: _PathsDLike) -> None: ...
    def add_clip(self, clips: _PathsDLike) -> None: ...
    def set_z_callback(self, callback: _ZCallbackD | None) -> None: ...
    def execute(self, clip_type: ClipType, fill_rule: FillRule) -> tuple[_PathsD, _PathsD]: ...
    def execute_tree(
        self, clip_type: ClipType, fill_rule: FillRule
    ) -> tuple[PolyPathD, _PathsD]: ...

# --- offsetting -------------------------------------------------------------------------------

class ClipperOffset:
    miter_limit: float
    arc_tolerance: float
    preserve_collinear: bool
    reverse_solution: bool
    def __init__(
        self,
        miter_limit: float = 2.0,
        arc_tolerance: float = 0.0,
        preserve_collinear: bool = False,
        reverse_solution: bool = False,
    ) -> None: ...
    @property
    def error_code(self) -> int: ...
    def clear(self) -> None: ...
    def add_path(self, path: _Path64Like, jt_: JoinType, et_: EndType) -> None: ...
    def add_paths(self, paths: _Paths64Like, jt_: JoinType, et_: EndType) -> None: ...
    def execute(self, delta: float | _DeltaCallback | None) -> _Paths64: ...
    def execute_tree(self, delta: float) -> PolyPath64: ...
    def set_delta_callback(self, callback: _DeltaCallback | None) -> None: ...
    def set_z_callback(self, callback: _ZCallback64 | None) -> None: ...

# --- rectangular clipping ----------------------------------------------------------------------

class RectClip64:
    def __init__(self, rect: Rect64) -> None: ...
    def execute(self, paths: _Paths64Like) -> _Paths64: ...

class RectClipLines64(RectClip64):
    def __init__(self, rect: Rect64) -> None: ...
    def execute(self, paths: _Paths64Like) -> _Paths64: ...

# --- clipper.core.h ------------------------------------------------------------------------------

def area(path: _GeometryLike) -> float: ...
def is_positive(poly: _PathDLike) -> bool: ...
@overload
def get_bounds(path: _Path64Like | _Paths64Like) -> Rect64: ...
@overload
def get_bounds(path: _PathDLike | _PathsDLike) -> RectD: ...
def point_in_polygon(pt: _PointDLike, polygon: _PathDLike) -> PointInPolygonResult: ...
@overload
def cross_product(pt1: _PointDLike, pt2: _PointDLike, pt3: _PointDLike) -> float: ...
@overload
def cross_product(vec1: _PointDLike, vec2: _PointDLike) -> float: ...
@overload
def dot_product(pt1: _PointDLike, pt2: _PointDLike, pt3: _PointDLike) -> float: ...
@overload
def dot_product(vec1: _PointDLike, vec2: _PointDLike) -> float: ...
def cross_product_sign(pt1: _PointDLike, pt2: _PointDLike, pt3: _PointDLike) -> int: ...
def is_collinear(pt1: _PointDLike, shared_pt: _PointDLike, pt2: _PointDLike) -> bool: ...
def distance_sqr(pt1: _PointDLike, pt2: _PointDLike) -> float: ...
def perpendic_dist_from_line_sqrd(
    pt: _PointDLike, line1: _PointDLike, line2: _PointDLike
) -> float: ...
@overload
def mid_point(p1: _Point64Like, p2: _Point64Like) -> _Point64: ...
@overload
def mid_point(p1: _PointDLike, p2: _PointDLike) -> _PointD: ...
def near_equal(p1: _PointDLike, p2: _PointDLike, max_dist_sqrd: float) -> bool: ...
@overload
def strip_near_equal(
    path: _Path64Like, max_dist_sqrd: float, is_closed_path: bool
) -> _Path64: ...
@overload
def strip_near_equal(
    path: _Paths64Like, max_dist_sqrd: float, is_closed_path: bool
) -> _Paths64: ...
@overload
def strip_near_equal(path: _PathDLike, max_dist_sqrd: float, is_closed_path: bool) -> _PathD: ...
@overload
def strip_near_equal(
    path: _PathsDLike, max_dist_sqrd: float, is_closed_path: bool
) -> _PathsD: ...
@overload
def strip_duplicates(path: _Path64Like, is_closed_path: bool) -> _Path64: ...
@overload
def strip_duplicates(path: _Paths64Like, is_closed_path: bool) -> _Paths64: ...
@overload
def strip_duplicates(path: _PathDLike, is_closed_path: bool) -> _PathD: ...
@overload
def strip_duplicates(path: _PathsDLike, is_closed_path: bool) -> _PathsD: ...
@overload
def translate_point(pt: _Point64Like, dx: float, dy: float) -> _Point64: ...
@overload
def translate_point(pt: _PointDLike, dx: float, dy: float) -> _PointD: ...
@overload
def reflect_point(pt: _Point64Like, pivot: _Point64Like) -> _Point64: ...
@overload
def reflect_point(pt: _PointDLike, pivot: _PointDLike) -> _PointD: ...
def segments_intersect(
    seg1a: _Point64Like,
    seg1b: _Point64Like,
    seg2a: _Point64Like,
    seg2b: _Point64Like,
    inclusive: bool = False,
) -> bool: ...
@overload
def get_closest_point_on_segment(
    off_pt: _Point64Like, seg1: _Point64Like, seg2: _Point64Like
) -> _Point64: ...
@overload
def get_closest_point_on_segment(
    off_pt: _PointDLike, seg1: _PointDLike, seg2: _PointDLike
) -> _PointD: ...

# --- clipper.h -------------------------------------------------------------------------------------

@overload
def boolean_op(
    cliptype: ClipType, fillrule: FillRule, subjects: _Paths64Like, clips: _Paths64Like
) -> _Paths64: ...
@overload
def boolean_op(
    cliptype: ClipType,
    fillrule: FillRule,
    subjects: _PathsDLike,
    clips: _PathsDLike,
    precision: int | None = None,
) -> _PathsD: ...
@overload
def boolean_op_tree(
    cliptype: ClipType, fillrule: FillRule, subjects: _Paths64Like, clips: _Paths64Like
) -> PolyPath64: ...
@overload
def boolean_op_tree(
    cliptype: ClipType,
    fillrule: FillRule,
    subjects: _PathsDLike,
    clips: _PathsDLike,
    precision: int | None = None,
) -> PolyPathD: ...
@overload
def intersect(subjects: _Paths64Like, clips: _Paths64Like, fillrule: FillRule) -> _Paths64: ...
@overload
def intersect(
    subjects: _PathsDLike,
    clips: _PathsDLike,
    fillrule: FillRule,
    decimal_prec: int | None = None,
) -> _PathsD: ...
@overload
def union(subjects: _Paths64Like, fillrule: FillRule) -> _Paths64: ...
@overload
def union(
    subjects: _PathsDLike, fillrule: FillRule, precision: int | None = None
) -> _PathsD: ...
@overload
def union(subjects: _Paths64Like, clips: _Paths64Like, fillrule: FillRule) -> _Paths64: ...
@overload
def union(
    subjects: _PathsDLike,
    clips: _PathsDLike,
    fillrule: FillRule,
    decimal_prec: int | None = None,
) -> _PathsD: ...
@overload
def difference(subjects: _Paths64Like, clips: _Paths64Like, fillrule: FillRule) -> _Paths64: ...
@overload
def difference(
    subjects: _PathsDLike,
    clips: _PathsDLike,
    fillrule: FillRule,
    decimal_prec: int | None = None,
) -> _PathsD: ...
@overload
def xor(subjects: _Paths64Like, clips: _Paths64Like, fillrule: FillRule) -> _Paths64: ...
@overload
def xor(
    subjects: _PathsDLike,
    clips: _PathsDLike,
    fillrule: FillRule,
    decimal_prec: int | None = None,
) -> _PathsD: ...
@overload
def translate_path(path: _Path64Like, dx: int, dy: int) -> _Path64: ...
@overload
def translate_path(path: _PathDLike, dx: float, dy: float) -> _PathD: ...
@overload
def translate_paths(paths: _Paths64Like, dx: int, dy: int) -> _Paths64: ...
@overload
def translate_paths(paths: _PathsDLike, dx: float, dy: float) -> _PathsD: ...
def poly_tree_to_paths64(polytree: PolyPath64) -> _Paths64: ...
def poly_tree_to_paths_d(polytree: PolyPathD) -> _PathsD: ...
def check_polytree_fully_contains_children(polytree: PolyPath64) -> bool: ...
def make_path(list: Sequence[int] | NDArray[np.integer[Any]]) -> _Path64: ...
def make_path_d(
    list: Sequence[float] | NDArray[np.floating[Any]] | NDArray[np.integer[Any]],
) -> _PathD: ...
@overload
def trim_collinear(path: _Path64Like, *, is_open_path: bool = False) -> _Path64: ...
@overload
def trim_collinear(path: _PathDLike, *, precision: int, is_open_path: bool = False) -> _PathD: ...
def distance(pt1: _PointDLike, pt2: _PointDLike) -> float: ...
def length(path: _PathDLike, is_closed_path: bool = False) -> float: ...
def near_collinear(
    pt1: _PointDLike, pt2: _PointDLike, pt3: _PointDLike, sin_sqrd_min_angle_rads: float
) -> bool: ...
@overload
def ellipse(rect: Rect64, steps: int = 0) -> _Path64: ...
@overload
def ellipse(rect: RectD, steps: int = 0) -> _PathD: ...
@overload
def ellipse(
    center: _Point64Like, radius_x: float, radius_y: float = 0, steps: int = 0
) -> _Path64: ...
@overload
def ellipse(
    center: _PointDLike, radius_x: float, radius_y: float = 0, steps: int = 0
) -> _PathD: ...
@overload
def simplify_path(path: _Path64Like, epsilon: float, is_closed_path: bool = True) -> _Path64: ...
@overload
def simplify_path(path: _PathDLike, epsilon: float, is_closed_path: bool = True) -> _PathD: ...
@overload
def simplify_paths(
    paths: _Paths64Like, epsilon: float, is_closed_path: bool = True
) -> _Paths64: ...
@overload
def simplify_paths(
    paths: _PathsDLike, epsilon: float, is_closed_path: bool = True
) -> _PathsD: ...
def path2_contains_path1(path1: _PathDLike, path2: _PathDLike) -> bool: ...
@overload
def ramer_douglas_peucker(path: _Path64Like, epsilon: float) -> _Path64: ...
@overload
def ramer_douglas_peucker(path: _Paths64Like, epsilon: float) -> _Paths64: ...
@overload
def ramer_douglas_peucker(path: _PathDLike, epsilon: float) -> _PathD: ...
@overload
def ramer_douglas_peucker(path: _PathsDLike, epsilon: float) -> _PathsD: ...

# --- clipper.offset.h --------------------------------------------------------------------------------

@overload
def inflate_paths(
    paths: _Paths64Like,
    delta: float,
    jt: JoinType,
    et: EndType,
    miter_limit: float = 2.0,
    *,
    arc_tolerance: float = 0.0,
) -> _Paths64: ...
@overload
def inflate_paths(
    paths: _PathsDLike,
    delta: float,
    jt: JoinType,
    et: EndType,
    miter_limit: float = 2.0,
    *,
    precision: int | None = None,
    arc_tolerance: float = 0.0,
) -> _PathsD: ...

# --- clipper.rectclip.h ------------------------------------------------------------------------------

@overload
def rect_clip(rect: Rect64, path: _Path64Like | _Paths64Like) -> _Paths64: ...
@overload
def rect_clip(
    rect: RectD, path: _PathDLike | _PathsDLike, precision: int | None = None
) -> _PathsD: ...
@overload
def rect_clip_lines(rect: Rect64, line: _Path64Like | _Paths64Like) -> _Paths64: ...
@overload
def rect_clip_lines(
    rect: RectD, line: _PathDLike | _PathsDLike, precision: int | None = None
) -> _PathsD: ...

# --- clipper.minkowski.h -----------------------------------------------------------------------------

@overload
def minkowski_sum(pattern: _Path64Like, path: _Path64Like, is_closed: bool) -> _Paths64: ...
@overload
def minkowski_sum(
    pattern: _PathDLike, path: _PathDLike, is_closed: bool, decimal_places: int | None = None
) -> _PathsD: ...
@overload
def minkowski_diff(pattern: _Path64Like, path: _Path64Like, is_closed: bool) -> _Paths64: ...
@overload
def minkowski_diff(
    pattern: _PathDLike, path: _PathDLike, is_closed: bool, decimal_places: int | None = None
) -> _PathsD: ...

# --- clipper.triangulation.h -------------------------------------------------------------------------

@overload
def triangulate(
    pp: _Paths64Like, *, use_delaunay: bool = True
) -> tuple[TriangulateResult, _Paths64]: ...
@overload
def triangulate(
    pp: _PathsDLike, *, dec_places: int, use_delaunay: bool = True
) -> tuple[TriangulateResult, _PathsD]: ...
